// flow-typed signature: 735c446e158dd8c61d50da45ab2144cf
// flow-typed version: <<STUB>>/bfx-api-node-util_v^1.0.8/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bfx-api-node-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bfx-api-node-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bfx-api-node-util/lib/gen_auth_sig' {
  declare module.exports: any;
}

declare module 'bfx-api-node-util/lib/is_class' {
  declare module.exports: any;
}

declare module 'bfx-api-node-util/lib/is_snapshot' {
  declare module.exports: any;
}

declare module 'bfx-api-node-util/lib/nonce' {
  declare module.exports: any;
}

declare module 'bfx-api-node-util/lib/pad_candles' {
  declare module.exports: any;
}

declare module 'bfx-api-node-util/lib/precision' {
  declare module.exports: any;
}

declare module 'bfx-api-node-util/test/lib/is_class' {
  declare module.exports: any;
}

declare module 'bfx-api-node-util/test/lib/is_snapshot' {
  declare module.exports: any;
}

declare module 'bfx-api-node-util/test/lib/nonce' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bfx-api-node-util/index' {
  declare module.exports: $Exports<'bfx-api-node-util'>;
}
declare module 'bfx-api-node-util/index.js' {
  declare module.exports: $Exports<'bfx-api-node-util'>;
}
declare module 'bfx-api-node-util/lib/gen_auth_sig.js' {
  declare module.exports: $Exports<'bfx-api-node-util/lib/gen_auth_sig'>;
}
declare module 'bfx-api-node-util/lib/is_class.js' {
  declare module.exports: $Exports<'bfx-api-node-util/lib/is_class'>;
}
declare module 'bfx-api-node-util/lib/is_snapshot.js' {
  declare module.exports: $Exports<'bfx-api-node-util/lib/is_snapshot'>;
}
declare module 'bfx-api-node-util/lib/nonce.js' {
  declare module.exports: $Exports<'bfx-api-node-util/lib/nonce'>;
}
declare module 'bfx-api-node-util/lib/pad_candles.js' {
  declare module.exports: $Exports<'bfx-api-node-util/lib/pad_candles'>;
}
declare module 'bfx-api-node-util/lib/precision.js' {
  declare module.exports: $Exports<'bfx-api-node-util/lib/precision'>;
}
declare module 'bfx-api-node-util/test/lib/is_class.js' {
  declare module.exports: $Exports<'bfx-api-node-util/test/lib/is_class'>;
}
declare module 'bfx-api-node-util/test/lib/is_snapshot.js' {
  declare module.exports: $Exports<'bfx-api-node-util/test/lib/is_snapshot'>;
}
declare module 'bfx-api-node-util/test/lib/nonce.js' {
  declare module.exports: $Exports<'bfx-api-node-util/test/lib/nonce'>;
}
