// flow-typed signature: a7df624bba14e0521929f3cbe01581cb
// flow-typed version: <<STUB>>/bfx-hf-util_v^1.0.6/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bfx-hf-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bfx-hf-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bfx-hf-util/dist' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/candles/align_range_mts' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/candles/candle_width' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/candles/chunks_for_range' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/candles' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/candles/preprocess_remote_candles' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/candles/time_frames' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/catch_uncaught_errors' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/data/currencies' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/data/symbols' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/data/time_frames' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/data/wallet_types' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/on_exit' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/dist/lib/range_string' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/candles/align_range_mts' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/candles/candle_width' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/candles/chunks_for_range' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/candles' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/candles/preprocess_remote_candles' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/candles/time_frames' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/catch_uncaught_errors' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/data/currencies' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/data/symbols' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/data/time_frames' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/data/wallet_types' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/on_exit' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/lib/range_string' {
  declare module.exports: any;
}

declare module 'bfx-hf-util/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bfx-hf-util/dist/index' {
  declare module.exports: $Exports<'bfx-hf-util/dist'>;
}
declare module 'bfx-hf-util/dist/index.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist'>;
}
declare module 'bfx-hf-util/dist/lib/candles/align_range_mts.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/candles/align_range_mts'>;
}
declare module 'bfx-hf-util/dist/lib/candles/candle_width.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/candles/candle_width'>;
}
declare module 'bfx-hf-util/dist/lib/candles/chunks_for_range.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/candles/chunks_for_range'>;
}
declare module 'bfx-hf-util/dist/lib/candles/index' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/candles'>;
}
declare module 'bfx-hf-util/dist/lib/candles/index.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/candles'>;
}
declare module 'bfx-hf-util/dist/lib/candles/preprocess_remote_candles.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/candles/preprocess_remote_candles'>;
}
declare module 'bfx-hf-util/dist/lib/candles/time_frames.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/candles/time_frames'>;
}
declare module 'bfx-hf-util/dist/lib/catch_uncaught_errors.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/catch_uncaught_errors'>;
}
declare module 'bfx-hf-util/dist/lib/data/currencies.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/data/currencies'>;
}
declare module 'bfx-hf-util/dist/lib/data/symbols.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/data/symbols'>;
}
declare module 'bfx-hf-util/dist/lib/data/time_frames.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/data/time_frames'>;
}
declare module 'bfx-hf-util/dist/lib/data/wallet_types.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/data/wallet_types'>;
}
declare module 'bfx-hf-util/dist/lib/index' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib'>;
}
declare module 'bfx-hf-util/dist/lib/index.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib'>;
}
declare module 'bfx-hf-util/dist/lib/on_exit.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/on_exit'>;
}
declare module 'bfx-hf-util/dist/lib/range_string.js' {
  declare module.exports: $Exports<'bfx-hf-util/dist/lib/range_string'>;
}
declare module 'bfx-hf-util/index' {
  declare module.exports: $Exports<'bfx-hf-util'>;
}
declare module 'bfx-hf-util/index.js' {
  declare module.exports: $Exports<'bfx-hf-util'>;
}
declare module 'bfx-hf-util/lib/candles/align_range_mts.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/candles/align_range_mts'>;
}
declare module 'bfx-hf-util/lib/candles/candle_width.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/candles/candle_width'>;
}
declare module 'bfx-hf-util/lib/candles/chunks_for_range.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/candles/chunks_for_range'>;
}
declare module 'bfx-hf-util/lib/candles/index' {
  declare module.exports: $Exports<'bfx-hf-util/lib/candles'>;
}
declare module 'bfx-hf-util/lib/candles/index.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/candles'>;
}
declare module 'bfx-hf-util/lib/candles/preprocess_remote_candles.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/candles/preprocess_remote_candles'>;
}
declare module 'bfx-hf-util/lib/candles/time_frames.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/candles/time_frames'>;
}
declare module 'bfx-hf-util/lib/catch_uncaught_errors.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/catch_uncaught_errors'>;
}
declare module 'bfx-hf-util/lib/data/currencies.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/data/currencies'>;
}
declare module 'bfx-hf-util/lib/data/symbols.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/data/symbols'>;
}
declare module 'bfx-hf-util/lib/data/time_frames.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/data/time_frames'>;
}
declare module 'bfx-hf-util/lib/data/wallet_types.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/data/wallet_types'>;
}
declare module 'bfx-hf-util/lib/index' {
  declare module.exports: $Exports<'bfx-hf-util/lib'>;
}
declare module 'bfx-hf-util/lib/index.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib'>;
}
declare module 'bfx-hf-util/lib/on_exit.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/on_exit'>;
}
declare module 'bfx-hf-util/lib/range_string.js' {
  declare module.exports: $Exports<'bfx-hf-util/lib/range_string'>;
}
declare module 'bfx-hf-util/webpack.config.js' {
  declare module.exports: $Exports<'bfx-hf-util/webpack.config'>;
}
