// flow-typed signature: 8b439f84134814a1b006fbe791211175
// flow-typed version: <<STUB>>/bfx-api-node-models_v^1.2.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bfx-api-node-models'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bfx-api-node-models' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bfx-api-node-models/examples/order' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/alert' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/balance_info' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/candle' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/currency' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/funding_credit' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/funding_info' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/funding_loan' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/funding_offer' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/funding_ticker_hist' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/funding_ticker' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/funding_trade' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/ledger_entry' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/liquidations' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/login' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/margin_info' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/model' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/movement' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/notification' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/order_book' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/order' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/position' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/public_trade' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/status_messages_deriv' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/trade' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/trading_ticker_hist' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/trading_ticker' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/user_info' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/util/assign_from_collection_or_instance' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/util/is_collection' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/validators/amount' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/validators/bool' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/validators/currency' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/validators/date' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/validators/number' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/validators/price' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/validators/string' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/validators/symbol' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/wallet_hist' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/lib/wallet' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/helpers/test_model_validation' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/helpers/test_model' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/alert' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/balance_info' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/candle' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/currency' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/funding_credit' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/funding_info' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/funding_loan' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/funding_offer' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/funding_ticker_hist' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/funding_ticker' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/funding_trade' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/ledger_entry' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/liquidations' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/login' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/margin_info' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/model' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/movement' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/notification' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/order_book' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/order' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/position' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/public_trade' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/status_messages_deriv' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/trade' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/trading_ticker_hist' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/trading_ticker' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/user_info' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/wallet_hist' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/models/wallet' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/util/assign_from_collection_or_instance' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/util/is_collection' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/validators/amount' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/validators/bool' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/validators/currency' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/validators/date' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/validators/number' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/validators/price' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/validators/string' {
  declare module.exports: any;
}

declare module 'bfx-api-node-models/test/lib/validators/symbol' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bfx-api-node-models/examples/order.js' {
  declare module.exports: $Exports<'bfx-api-node-models/examples/order'>;
}
declare module 'bfx-api-node-models/index' {
  declare module.exports: $Exports<'bfx-api-node-models'>;
}
declare module 'bfx-api-node-models/index.js' {
  declare module.exports: $Exports<'bfx-api-node-models'>;
}
declare module 'bfx-api-node-models/lib/alert.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/alert'>;
}
declare module 'bfx-api-node-models/lib/balance_info.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/balance_info'>;
}
declare module 'bfx-api-node-models/lib/candle.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/candle'>;
}
declare module 'bfx-api-node-models/lib/currency.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/currency'>;
}
declare module 'bfx-api-node-models/lib/funding_credit.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/funding_credit'>;
}
declare module 'bfx-api-node-models/lib/funding_info.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/funding_info'>;
}
declare module 'bfx-api-node-models/lib/funding_loan.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/funding_loan'>;
}
declare module 'bfx-api-node-models/lib/funding_offer.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/funding_offer'>;
}
declare module 'bfx-api-node-models/lib/funding_ticker_hist.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/funding_ticker_hist'>;
}
declare module 'bfx-api-node-models/lib/funding_ticker.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/funding_ticker'>;
}
declare module 'bfx-api-node-models/lib/funding_trade.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/funding_trade'>;
}
declare module 'bfx-api-node-models/lib/index' {
  declare module.exports: $Exports<'bfx-api-node-models/lib'>;
}
declare module 'bfx-api-node-models/lib/index.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib'>;
}
declare module 'bfx-api-node-models/lib/ledger_entry.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/ledger_entry'>;
}
declare module 'bfx-api-node-models/lib/liquidations.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/liquidations'>;
}
declare module 'bfx-api-node-models/lib/login.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/login'>;
}
declare module 'bfx-api-node-models/lib/margin_info.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/margin_info'>;
}
declare module 'bfx-api-node-models/lib/model.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/model'>;
}
declare module 'bfx-api-node-models/lib/movement.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/movement'>;
}
declare module 'bfx-api-node-models/lib/notification.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/notification'>;
}
declare module 'bfx-api-node-models/lib/order_book.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/order_book'>;
}
declare module 'bfx-api-node-models/lib/order.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/order'>;
}
declare module 'bfx-api-node-models/lib/position.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/position'>;
}
declare module 'bfx-api-node-models/lib/public_trade.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/public_trade'>;
}
declare module 'bfx-api-node-models/lib/status_messages_deriv.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/status_messages_deriv'>;
}
declare module 'bfx-api-node-models/lib/trade.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/trade'>;
}
declare module 'bfx-api-node-models/lib/trading_ticker_hist.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/trading_ticker_hist'>;
}
declare module 'bfx-api-node-models/lib/trading_ticker.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/trading_ticker'>;
}
declare module 'bfx-api-node-models/lib/user_info.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/user_info'>;
}
declare module 'bfx-api-node-models/lib/util/assign_from_collection_or_instance.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/util/assign_from_collection_or_instance'>;
}
declare module 'bfx-api-node-models/lib/util/is_collection.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/util/is_collection'>;
}
declare module 'bfx-api-node-models/lib/validators/amount.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/validators/amount'>;
}
declare module 'bfx-api-node-models/lib/validators/bool.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/validators/bool'>;
}
declare module 'bfx-api-node-models/lib/validators/currency.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/validators/currency'>;
}
declare module 'bfx-api-node-models/lib/validators/date.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/validators/date'>;
}
declare module 'bfx-api-node-models/lib/validators/number.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/validators/number'>;
}
declare module 'bfx-api-node-models/lib/validators/price.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/validators/price'>;
}
declare module 'bfx-api-node-models/lib/validators/string.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/validators/string'>;
}
declare module 'bfx-api-node-models/lib/validators/symbol.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/validators/symbol'>;
}
declare module 'bfx-api-node-models/lib/wallet_hist.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/wallet_hist'>;
}
declare module 'bfx-api-node-models/lib/wallet.js' {
  declare module.exports: $Exports<'bfx-api-node-models/lib/wallet'>;
}
declare module 'bfx-api-node-models/test/helpers/test_model_validation.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/helpers/test_model_validation'>;
}
declare module 'bfx-api-node-models/test/helpers/test_model.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/helpers/test_model'>;
}
declare module 'bfx-api-node-models/test/lib/models/alert.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/alert'>;
}
declare module 'bfx-api-node-models/test/lib/models/balance_info.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/balance_info'>;
}
declare module 'bfx-api-node-models/test/lib/models/candle.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/candle'>;
}
declare module 'bfx-api-node-models/test/lib/models/currency.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/currency'>;
}
declare module 'bfx-api-node-models/test/lib/models/funding_credit.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/funding_credit'>;
}
declare module 'bfx-api-node-models/test/lib/models/funding_info.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/funding_info'>;
}
declare module 'bfx-api-node-models/test/lib/models/funding_loan.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/funding_loan'>;
}
declare module 'bfx-api-node-models/test/lib/models/funding_offer.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/funding_offer'>;
}
declare module 'bfx-api-node-models/test/lib/models/funding_ticker_hist.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/funding_ticker_hist'>;
}
declare module 'bfx-api-node-models/test/lib/models/funding_ticker.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/funding_ticker'>;
}
declare module 'bfx-api-node-models/test/lib/models/funding_trade.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/funding_trade'>;
}
declare module 'bfx-api-node-models/test/lib/models/ledger_entry.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/ledger_entry'>;
}
declare module 'bfx-api-node-models/test/lib/models/liquidations.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/liquidations'>;
}
declare module 'bfx-api-node-models/test/lib/models/login.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/login'>;
}
declare module 'bfx-api-node-models/test/lib/models/margin_info.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/margin_info'>;
}
declare module 'bfx-api-node-models/test/lib/models/model.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/model'>;
}
declare module 'bfx-api-node-models/test/lib/models/movement.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/movement'>;
}
declare module 'bfx-api-node-models/test/lib/models/notification.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/notification'>;
}
declare module 'bfx-api-node-models/test/lib/models/order_book.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/order_book'>;
}
declare module 'bfx-api-node-models/test/lib/models/order.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/order'>;
}
declare module 'bfx-api-node-models/test/lib/models/position.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/position'>;
}
declare module 'bfx-api-node-models/test/lib/models/public_trade.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/public_trade'>;
}
declare module 'bfx-api-node-models/test/lib/models/status_messages_deriv.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/status_messages_deriv'>;
}
declare module 'bfx-api-node-models/test/lib/models/trade.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/trade'>;
}
declare module 'bfx-api-node-models/test/lib/models/trading_ticker_hist.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/trading_ticker_hist'>;
}
declare module 'bfx-api-node-models/test/lib/models/trading_ticker.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/trading_ticker'>;
}
declare module 'bfx-api-node-models/test/lib/models/user_info.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/user_info'>;
}
declare module 'bfx-api-node-models/test/lib/models/wallet_hist.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/wallet_hist'>;
}
declare module 'bfx-api-node-models/test/lib/models/wallet.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/models/wallet'>;
}
declare module 'bfx-api-node-models/test/lib/util/assign_from_collection_or_instance.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/util/assign_from_collection_or_instance'>;
}
declare module 'bfx-api-node-models/test/lib/util/is_collection.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/util/is_collection'>;
}
declare module 'bfx-api-node-models/test/lib/validators/amount.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/validators/amount'>;
}
declare module 'bfx-api-node-models/test/lib/validators/bool.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/validators/bool'>;
}
declare module 'bfx-api-node-models/test/lib/validators/currency.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/validators/currency'>;
}
declare module 'bfx-api-node-models/test/lib/validators/date.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/validators/date'>;
}
declare module 'bfx-api-node-models/test/lib/validators/number.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/validators/number'>;
}
declare module 'bfx-api-node-models/test/lib/validators/price.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/validators/price'>;
}
declare module 'bfx-api-node-models/test/lib/validators/string.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/validators/string'>;
}
declare module 'bfx-api-node-models/test/lib/validators/symbol.js' {
  declare module.exports: $Exports<'bfx-api-node-models/test/lib/validators/symbol'>;
}
