// flow-typed signature: e983a28cc9b3c60e106cc4dcfd44a802
// flow-typed version: <<STUB>>/bfx-api-node-rest_v^3.0.9/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bfx-api-node-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bfx-api-node-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bfx-api-node-rest/docs/scripts/collapse' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/docs/scripts/nav' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/docs/scripts/polyfill' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/docs/scripts/search' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/examples/candles' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/examples/trades' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/lib/rest1' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/lib/rest2' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/test/lib/rest-1-integration' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/test/lib/rest-2-integration' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/test/lib/rest-2-issue-80-argument-length' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/test/lib/rest-2-smoke-test' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/test/lib/rest-2-unit' {
  declare module.exports: any;
}

declare module 'bfx-api-node-rest/test/lib/rest1' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bfx-api-node-rest/docs/scripts/collapse.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/docs/scripts/collapse'>;
}
declare module 'bfx-api-node-rest/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/docs/scripts/linenumber'>;
}
declare module 'bfx-api-node-rest/docs/scripts/nav.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/docs/scripts/nav'>;
}
declare module 'bfx-api-node-rest/docs/scripts/polyfill.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/docs/scripts/polyfill'>;
}
declare module 'bfx-api-node-rest/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/docs/scripts/prettify/lang-css'>;
}
declare module 'bfx-api-node-rest/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/docs/scripts/prettify/prettify'>;
}
declare module 'bfx-api-node-rest/docs/scripts/search.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/docs/scripts/search'>;
}
declare module 'bfx-api-node-rest/examples/candles.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/examples/candles'>;
}
declare module 'bfx-api-node-rest/examples/trades.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/examples/trades'>;
}
declare module 'bfx-api-node-rest/index' {
  declare module.exports: $Exports<'bfx-api-node-rest'>;
}
declare module 'bfx-api-node-rest/index.js' {
  declare module.exports: $Exports<'bfx-api-node-rest'>;
}
declare module 'bfx-api-node-rest/lib/rest1.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/lib/rest1'>;
}
declare module 'bfx-api-node-rest/lib/rest2.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/lib/rest2'>;
}
declare module 'bfx-api-node-rest/test/lib/rest-1-integration.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/test/lib/rest-1-integration'>;
}
declare module 'bfx-api-node-rest/test/lib/rest-2-integration.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/test/lib/rest-2-integration'>;
}
declare module 'bfx-api-node-rest/test/lib/rest-2-issue-80-argument-length.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/test/lib/rest-2-issue-80-argument-length'>;
}
declare module 'bfx-api-node-rest/test/lib/rest-2-smoke-test.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/test/lib/rest-2-smoke-test'>;
}
declare module 'bfx-api-node-rest/test/lib/rest-2-unit.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/test/lib/rest-2-unit'>;
}
declare module 'bfx-api-node-rest/test/lib/rest1.js' {
  declare module.exports: $Exports<'bfx-api-node-rest/test/lib/rest1'>;
}
