// flow-typed signature: 0042a739bcd3e78345559c8fa4fb4077
// flow-typed version: <<STUB>>/bfx-hf-indicators_v^2.0.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bfx-hf-indicators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bfx-hf-indicators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bfx-hf-indicators/dist' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/acceleration' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/accumulation_distribution' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/accumulative_swing_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/alma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/aroon' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/atr' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/average_directional_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/awesome_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/balance_of_power' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/bbands' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/chaikin_money_flow' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/chaikin_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/chande_momentum_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/coppock_curve' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/detrended_price_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/donchian_channels' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/ease_of_movement' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/ema_vol' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/ema' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/envelope' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/indicator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/know_sure_thing' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/macd' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/mass_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/momentum' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/net_volume' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/normalised_atr' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/on_balance_volume' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/price_channel' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/price_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/price_volume_trend' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/relative_vigor_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/relative_volatility_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/roc' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/rsi' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/sma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/stddev' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/stochastic_rsi' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/stochastic' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/trix' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/true_strength_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/volume_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/vwap' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/vwma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/wilders_ma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/williams_r' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/dist/lib/wma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/examples/ema' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/acceleration' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/accumulation_distribution' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/accumulative_swing_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/alma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/aroon' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/atr' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/average_directional_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/awesome_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/balance_of_power' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/bbands' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/chaikin_money_flow' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/chaikin_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/chande_momentum_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/coppock_curve' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/detrended_price_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/donchian_channels' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/ease_of_movement' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/ema_vol' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/ema' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/envelope' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/indicator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/know_sure_thing' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/macd' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/mass_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/momentum' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/net_volume' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/normalised_atr' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/on_balance_volume' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/price_channel' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/price_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/price_volume_trend' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/relative_vigor_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/relative_volatility_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/roc' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/rsi' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/sma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/stddev' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/stochastic_rsi' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/stochastic' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/trix' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/true_strength_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/volume_oscillator' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/vwap' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/vwma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/wilders_ma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/williams_r' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/lib/wma' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/test/accumulative_swing_index' {
  declare module.exports: any;
}

declare module 'bfx-hf-indicators/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bfx-hf-indicators/dist/index' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist'>;
}
declare module 'bfx-hf-indicators/dist/index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist'>;
}
declare module 'bfx-hf-indicators/dist/lib/acceleration.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/acceleration'>;
}
declare module 'bfx-hf-indicators/dist/lib/accumulation_distribution.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/accumulation_distribution'>;
}
declare module 'bfx-hf-indicators/dist/lib/accumulative_swing_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/accumulative_swing_index'>;
}
declare module 'bfx-hf-indicators/dist/lib/alma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/alma'>;
}
declare module 'bfx-hf-indicators/dist/lib/aroon.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/aroon'>;
}
declare module 'bfx-hf-indicators/dist/lib/atr.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/atr'>;
}
declare module 'bfx-hf-indicators/dist/lib/average_directional_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/average_directional_index'>;
}
declare module 'bfx-hf-indicators/dist/lib/awesome_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/awesome_oscillator'>;
}
declare module 'bfx-hf-indicators/dist/lib/balance_of_power.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/balance_of_power'>;
}
declare module 'bfx-hf-indicators/dist/lib/bbands.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/bbands'>;
}
declare module 'bfx-hf-indicators/dist/lib/chaikin_money_flow.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/chaikin_money_flow'>;
}
declare module 'bfx-hf-indicators/dist/lib/chaikin_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/chaikin_oscillator'>;
}
declare module 'bfx-hf-indicators/dist/lib/chande_momentum_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/chande_momentum_oscillator'>;
}
declare module 'bfx-hf-indicators/dist/lib/coppock_curve.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/coppock_curve'>;
}
declare module 'bfx-hf-indicators/dist/lib/detrended_price_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/detrended_price_oscillator'>;
}
declare module 'bfx-hf-indicators/dist/lib/donchian_channels.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/donchian_channels'>;
}
declare module 'bfx-hf-indicators/dist/lib/ease_of_movement.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/ease_of_movement'>;
}
declare module 'bfx-hf-indicators/dist/lib/ema_vol.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/ema_vol'>;
}
declare module 'bfx-hf-indicators/dist/lib/ema.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/ema'>;
}
declare module 'bfx-hf-indicators/dist/lib/envelope.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/envelope'>;
}
declare module 'bfx-hf-indicators/dist/lib/indicator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/indicator'>;
}
declare module 'bfx-hf-indicators/dist/lib/know_sure_thing.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/know_sure_thing'>;
}
declare module 'bfx-hf-indicators/dist/lib/macd.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/macd'>;
}
declare module 'bfx-hf-indicators/dist/lib/mass_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/mass_index'>;
}
declare module 'bfx-hf-indicators/dist/lib/momentum.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/momentum'>;
}
declare module 'bfx-hf-indicators/dist/lib/net_volume.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/net_volume'>;
}
declare module 'bfx-hf-indicators/dist/lib/normalised_atr.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/normalised_atr'>;
}
declare module 'bfx-hf-indicators/dist/lib/on_balance_volume.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/on_balance_volume'>;
}
declare module 'bfx-hf-indicators/dist/lib/price_channel.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/price_channel'>;
}
declare module 'bfx-hf-indicators/dist/lib/price_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/price_oscillator'>;
}
declare module 'bfx-hf-indicators/dist/lib/price_volume_trend.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/price_volume_trend'>;
}
declare module 'bfx-hf-indicators/dist/lib/relative_vigor_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/relative_vigor_index'>;
}
declare module 'bfx-hf-indicators/dist/lib/relative_volatility_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/relative_volatility_index'>;
}
declare module 'bfx-hf-indicators/dist/lib/roc.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/roc'>;
}
declare module 'bfx-hf-indicators/dist/lib/rsi.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/rsi'>;
}
declare module 'bfx-hf-indicators/dist/lib/sma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/sma'>;
}
declare module 'bfx-hf-indicators/dist/lib/stddev.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/stddev'>;
}
declare module 'bfx-hf-indicators/dist/lib/stochastic_rsi.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/stochastic_rsi'>;
}
declare module 'bfx-hf-indicators/dist/lib/stochastic.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/stochastic'>;
}
declare module 'bfx-hf-indicators/dist/lib/trix.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/trix'>;
}
declare module 'bfx-hf-indicators/dist/lib/true_strength_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/true_strength_index'>;
}
declare module 'bfx-hf-indicators/dist/lib/volume_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/volume_oscillator'>;
}
declare module 'bfx-hf-indicators/dist/lib/vwap.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/vwap'>;
}
declare module 'bfx-hf-indicators/dist/lib/vwma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/vwma'>;
}
declare module 'bfx-hf-indicators/dist/lib/wilders_ma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/wilders_ma'>;
}
declare module 'bfx-hf-indicators/dist/lib/williams_r.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/williams_r'>;
}
declare module 'bfx-hf-indicators/dist/lib/wma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/dist/lib/wma'>;
}
declare module 'bfx-hf-indicators/examples/ema.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/examples/ema'>;
}
declare module 'bfx-hf-indicators/index' {
  declare module.exports: $Exports<'bfx-hf-indicators'>;
}
declare module 'bfx-hf-indicators/index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators'>;
}
declare module 'bfx-hf-indicators/lib/acceleration.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/acceleration'>;
}
declare module 'bfx-hf-indicators/lib/accumulation_distribution.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/accumulation_distribution'>;
}
declare module 'bfx-hf-indicators/lib/accumulative_swing_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/accumulative_swing_index'>;
}
declare module 'bfx-hf-indicators/lib/alma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/alma'>;
}
declare module 'bfx-hf-indicators/lib/aroon.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/aroon'>;
}
declare module 'bfx-hf-indicators/lib/atr.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/atr'>;
}
declare module 'bfx-hf-indicators/lib/average_directional_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/average_directional_index'>;
}
declare module 'bfx-hf-indicators/lib/awesome_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/awesome_oscillator'>;
}
declare module 'bfx-hf-indicators/lib/balance_of_power.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/balance_of_power'>;
}
declare module 'bfx-hf-indicators/lib/bbands.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/bbands'>;
}
declare module 'bfx-hf-indicators/lib/chaikin_money_flow.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/chaikin_money_flow'>;
}
declare module 'bfx-hf-indicators/lib/chaikin_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/chaikin_oscillator'>;
}
declare module 'bfx-hf-indicators/lib/chande_momentum_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/chande_momentum_oscillator'>;
}
declare module 'bfx-hf-indicators/lib/coppock_curve.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/coppock_curve'>;
}
declare module 'bfx-hf-indicators/lib/detrended_price_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/detrended_price_oscillator'>;
}
declare module 'bfx-hf-indicators/lib/donchian_channels.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/donchian_channels'>;
}
declare module 'bfx-hf-indicators/lib/ease_of_movement.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/ease_of_movement'>;
}
declare module 'bfx-hf-indicators/lib/ema_vol.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/ema_vol'>;
}
declare module 'bfx-hf-indicators/lib/ema.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/ema'>;
}
declare module 'bfx-hf-indicators/lib/envelope.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/envelope'>;
}
declare module 'bfx-hf-indicators/lib/indicator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/indicator'>;
}
declare module 'bfx-hf-indicators/lib/know_sure_thing.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/know_sure_thing'>;
}
declare module 'bfx-hf-indicators/lib/macd.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/macd'>;
}
declare module 'bfx-hf-indicators/lib/mass_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/mass_index'>;
}
declare module 'bfx-hf-indicators/lib/momentum.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/momentum'>;
}
declare module 'bfx-hf-indicators/lib/net_volume.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/net_volume'>;
}
declare module 'bfx-hf-indicators/lib/normalised_atr.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/normalised_atr'>;
}
declare module 'bfx-hf-indicators/lib/on_balance_volume.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/on_balance_volume'>;
}
declare module 'bfx-hf-indicators/lib/price_channel.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/price_channel'>;
}
declare module 'bfx-hf-indicators/lib/price_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/price_oscillator'>;
}
declare module 'bfx-hf-indicators/lib/price_volume_trend.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/price_volume_trend'>;
}
declare module 'bfx-hf-indicators/lib/relative_vigor_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/relative_vigor_index'>;
}
declare module 'bfx-hf-indicators/lib/relative_volatility_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/relative_volatility_index'>;
}
declare module 'bfx-hf-indicators/lib/roc.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/roc'>;
}
declare module 'bfx-hf-indicators/lib/rsi.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/rsi'>;
}
declare module 'bfx-hf-indicators/lib/sma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/sma'>;
}
declare module 'bfx-hf-indicators/lib/stddev.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/stddev'>;
}
declare module 'bfx-hf-indicators/lib/stochastic_rsi.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/stochastic_rsi'>;
}
declare module 'bfx-hf-indicators/lib/stochastic.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/stochastic'>;
}
declare module 'bfx-hf-indicators/lib/trix.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/trix'>;
}
declare module 'bfx-hf-indicators/lib/true_strength_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/true_strength_index'>;
}
declare module 'bfx-hf-indicators/lib/volume_oscillator.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/volume_oscillator'>;
}
declare module 'bfx-hf-indicators/lib/vwap.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/vwap'>;
}
declare module 'bfx-hf-indicators/lib/vwma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/vwma'>;
}
declare module 'bfx-hf-indicators/lib/wilders_ma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/wilders_ma'>;
}
declare module 'bfx-hf-indicators/lib/williams_r.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/williams_r'>;
}
declare module 'bfx-hf-indicators/lib/wma.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/lib/wma'>;
}
declare module 'bfx-hf-indicators/test/accumulative_swing_index.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/test/accumulative_swing_index'>;
}
declare module 'bfx-hf-indicators/webpack.config.js' {
  declare module.exports: $Exports<'bfx-hf-indicators/webpack.config'>;
}
