// flow-typed signature: 69fb42902379f98740da558f0b83d0c7
// flow-typed version: <<STUB>>/bitfinex-api-node_v^4.0.13/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitfinex-api-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitfinex-api-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitfinex-api-node/docs/scripts/collapse' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/docs/scripts/nav' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/docs/scripts/polyfill' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/docs/scripts/search' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/balances' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/claim_positions' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/close_positions' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/currencies' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/funding_credits' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/funding_info' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/funding_loans' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/funding_offers' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/ledgers' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/list_open_orders' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/margin_info' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/movements' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/order-history' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/positions' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/status' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/submit_funding_offer' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/submit_order' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/symbol-details' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/symbols' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/tickers' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/trade-history' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/transfer' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/rest2/wallet' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/util/arg_from_cli' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/util/args_from_env' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/util/debug_table' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/util/debug' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/util/run_example' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2_manager' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/atomic_order_update' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/auth' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/calc' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/cancel_all_buf' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/cancel_all' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/candles' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/funding_info' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/info_events' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/liquidations' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/notifications' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/notify_ui' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/ob_checksum' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/oc_multi' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/oco-order' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/order_book_viz' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/order_books' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/order_tif' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/orders' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/ox_multi' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/sequencing' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/tickers' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/examples/ws2/trades' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/lib/transports/ws2' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/lib/util' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/lib/util/is_class' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/lib/util/is_snapshot' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/lib/util/precision' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/lib/util/ws2' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/lib/ws2_manager' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/test/examples/args_from_env' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/test/examples/debug_table' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/test/examples/run_example' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/test' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/test/lib/transports/ws2-integration' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/test/lib/transports/ws2-unit' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/test/lib/util/is_class' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/test/lib/util/is_snapshot' {
  declare module.exports: any;
}

declare module 'bitfinex-api-node/test/lib/ws2_manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitfinex-api-node/docs/scripts/collapse.js' {
  declare module.exports: $Exports<'bitfinex-api-node/docs/scripts/collapse'>;
}
declare module 'bitfinex-api-node/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'bitfinex-api-node/docs/scripts/linenumber'>;
}
declare module 'bitfinex-api-node/docs/scripts/nav.js' {
  declare module.exports: $Exports<'bitfinex-api-node/docs/scripts/nav'>;
}
declare module 'bitfinex-api-node/docs/scripts/polyfill.js' {
  declare module.exports: $Exports<'bitfinex-api-node/docs/scripts/polyfill'>;
}
declare module 'bitfinex-api-node/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'bitfinex-api-node/docs/scripts/prettify/lang-css'>;
}
declare module 'bitfinex-api-node/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'bitfinex-api-node/docs/scripts/prettify/prettify'>;
}
declare module 'bitfinex-api-node/docs/scripts/search.js' {
  declare module.exports: $Exports<'bitfinex-api-node/docs/scripts/search'>;
}
declare module 'bitfinex-api-node/examples/rest2/balances.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/balances'>;
}
declare module 'bitfinex-api-node/examples/rest2/claim_positions.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/claim_positions'>;
}
declare module 'bitfinex-api-node/examples/rest2/close_positions.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/close_positions'>;
}
declare module 'bitfinex-api-node/examples/rest2/currencies.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/currencies'>;
}
declare module 'bitfinex-api-node/examples/rest2/funding_credits.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/funding_credits'>;
}
declare module 'bitfinex-api-node/examples/rest2/funding_info.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/funding_info'>;
}
declare module 'bitfinex-api-node/examples/rest2/funding_loans.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/funding_loans'>;
}
declare module 'bitfinex-api-node/examples/rest2/funding_offers.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/funding_offers'>;
}
declare module 'bitfinex-api-node/examples/rest2/ledgers.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/ledgers'>;
}
declare module 'bitfinex-api-node/examples/rest2/list_open_orders.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/list_open_orders'>;
}
declare module 'bitfinex-api-node/examples/rest2/margin_info.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/margin_info'>;
}
declare module 'bitfinex-api-node/examples/rest2/movements.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/movements'>;
}
declare module 'bitfinex-api-node/examples/rest2/order-history.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/order-history'>;
}
declare module 'bitfinex-api-node/examples/rest2/positions.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/positions'>;
}
declare module 'bitfinex-api-node/examples/rest2/status.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/status'>;
}
declare module 'bitfinex-api-node/examples/rest2/submit_funding_offer.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/submit_funding_offer'>;
}
declare module 'bitfinex-api-node/examples/rest2/submit_order.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/submit_order'>;
}
declare module 'bitfinex-api-node/examples/rest2/symbol-details.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/symbol-details'>;
}
declare module 'bitfinex-api-node/examples/rest2/symbols.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/symbols'>;
}
declare module 'bitfinex-api-node/examples/rest2/tickers.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/tickers'>;
}
declare module 'bitfinex-api-node/examples/rest2/trade-history.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/trade-history'>;
}
declare module 'bitfinex-api-node/examples/rest2/transfer.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/transfer'>;
}
declare module 'bitfinex-api-node/examples/rest2/wallet.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/rest2/wallet'>;
}
declare module 'bitfinex-api-node/examples/util/arg_from_cli.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/util/arg_from_cli'>;
}
declare module 'bitfinex-api-node/examples/util/args_from_env.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/util/args_from_env'>;
}
declare module 'bitfinex-api-node/examples/util/debug_table.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/util/debug_table'>;
}
declare module 'bitfinex-api-node/examples/util/debug.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/util/debug'>;
}
declare module 'bitfinex-api-node/examples/util/run_example.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/util/run_example'>;
}
declare module 'bitfinex-api-node/examples/ws2_manager.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2_manager'>;
}
declare module 'bitfinex-api-node/examples/ws2/atomic_order_update.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/atomic_order_update'>;
}
declare module 'bitfinex-api-node/examples/ws2/auth.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/auth'>;
}
declare module 'bitfinex-api-node/examples/ws2/calc.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/calc'>;
}
declare module 'bitfinex-api-node/examples/ws2/cancel_all_buf.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/cancel_all_buf'>;
}
declare module 'bitfinex-api-node/examples/ws2/cancel_all.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/cancel_all'>;
}
declare module 'bitfinex-api-node/examples/ws2/candles.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/candles'>;
}
declare module 'bitfinex-api-node/examples/ws2/funding_info.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/funding_info'>;
}
declare module 'bitfinex-api-node/examples/ws2/info_events.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/info_events'>;
}
declare module 'bitfinex-api-node/examples/ws2/liquidations.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/liquidations'>;
}
declare module 'bitfinex-api-node/examples/ws2/notifications.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/notifications'>;
}
declare module 'bitfinex-api-node/examples/ws2/notify_ui.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/notify_ui'>;
}
declare module 'bitfinex-api-node/examples/ws2/ob_checksum.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/ob_checksum'>;
}
declare module 'bitfinex-api-node/examples/ws2/oc_multi.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/oc_multi'>;
}
declare module 'bitfinex-api-node/examples/ws2/oco-order.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/oco-order'>;
}
declare module 'bitfinex-api-node/examples/ws2/order_book_viz.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/order_book_viz'>;
}
declare module 'bitfinex-api-node/examples/ws2/order_books.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/order_books'>;
}
declare module 'bitfinex-api-node/examples/ws2/order_tif.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/order_tif'>;
}
declare module 'bitfinex-api-node/examples/ws2/orders.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/orders'>;
}
declare module 'bitfinex-api-node/examples/ws2/ox_multi.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/ox_multi'>;
}
declare module 'bitfinex-api-node/examples/ws2/sequencing.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/sequencing'>;
}
declare module 'bitfinex-api-node/examples/ws2/tickers.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/tickers'>;
}
declare module 'bitfinex-api-node/examples/ws2/trades.js' {
  declare module.exports: $Exports<'bitfinex-api-node/examples/ws2/trades'>;
}
declare module 'bitfinex-api-node/index' {
  declare module.exports: $Exports<'bitfinex-api-node'>;
}
declare module 'bitfinex-api-node/index.js' {
  declare module.exports: $Exports<'bitfinex-api-node'>;
}
declare module 'bitfinex-api-node/lib/transports/ws2.js' {
  declare module.exports: $Exports<'bitfinex-api-node/lib/transports/ws2'>;
}
declare module 'bitfinex-api-node/lib/util/index' {
  declare module.exports: $Exports<'bitfinex-api-node/lib/util'>;
}
declare module 'bitfinex-api-node/lib/util/index.js' {
  declare module.exports: $Exports<'bitfinex-api-node/lib/util'>;
}
declare module 'bitfinex-api-node/lib/util/is_class.js' {
  declare module.exports: $Exports<'bitfinex-api-node/lib/util/is_class'>;
}
declare module 'bitfinex-api-node/lib/util/is_snapshot.js' {
  declare module.exports: $Exports<'bitfinex-api-node/lib/util/is_snapshot'>;
}
declare module 'bitfinex-api-node/lib/util/precision.js' {
  declare module.exports: $Exports<'bitfinex-api-node/lib/util/precision'>;
}
declare module 'bitfinex-api-node/lib/util/ws2.js' {
  declare module.exports: $Exports<'bitfinex-api-node/lib/util/ws2'>;
}
declare module 'bitfinex-api-node/lib/ws2_manager.js' {
  declare module.exports: $Exports<'bitfinex-api-node/lib/ws2_manager'>;
}
declare module 'bitfinex-api-node/test/examples/args_from_env.js' {
  declare module.exports: $Exports<'bitfinex-api-node/test/examples/args_from_env'>;
}
declare module 'bitfinex-api-node/test/examples/debug_table.js' {
  declare module.exports: $Exports<'bitfinex-api-node/test/examples/debug_table'>;
}
declare module 'bitfinex-api-node/test/examples/run_example.js' {
  declare module.exports: $Exports<'bitfinex-api-node/test/examples/run_example'>;
}
declare module 'bitfinex-api-node/test/index' {
  declare module.exports: $Exports<'bitfinex-api-node/test'>;
}
declare module 'bitfinex-api-node/test/index.js' {
  declare module.exports: $Exports<'bitfinex-api-node/test'>;
}
declare module 'bitfinex-api-node/test/lib/transports/ws2-integration.js' {
  declare module.exports: $Exports<'bitfinex-api-node/test/lib/transports/ws2-integration'>;
}
declare module 'bitfinex-api-node/test/lib/transports/ws2-unit.js' {
  declare module.exports: $Exports<'bitfinex-api-node/test/lib/transports/ws2-unit'>;
}
declare module 'bitfinex-api-node/test/lib/util/is_class.js' {
  declare module.exports: $Exports<'bitfinex-api-node/test/lib/util/is_class'>;
}
declare module 'bitfinex-api-node/test/lib/util/is_snapshot.js' {
  declare module.exports: $Exports<'bitfinex-api-node/test/lib/util/is_snapshot'>;
}
declare module 'bitfinex-api-node/test/lib/ws2_manager.js' {
  declare module.exports: $Exports<'bitfinex-api-node/test/lib/ws2_manager'>;
}
