// flow-typed signature: 63180de9b5c8384989919a3a39cddb15
// flow-typed version: <<STUB>>/p-iteration_v^1.1.8/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-iteration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-iteration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'p-iteration/lib/instance-methods' {
  declare module.exports: any;
}

declare module 'p-iteration/lib/static-methods' {
  declare module.exports: any;
}

// Filename aliases
declare module 'p-iteration/index' {
  declare module.exports: $Exports<'p-iteration'>;
}
declare module 'p-iteration/index.js' {
  declare module.exports: $Exports<'p-iteration'>;
}
declare module 'p-iteration/lib/instance-methods.js' {
  declare module.exports: $Exports<'p-iteration/lib/instance-methods'>;
}
declare module 'p-iteration/lib/static-methods.js' {
  declare module.exports: $Exports<'p-iteration/lib/static-methods'>;
}
