// flow-typed signature: c8a12ae799fd190eab636692be75b4dd
// flow-typed version: <<STUB>>/parse-duration_v^0.1.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-duration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-duration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parse-duration/index' {
  declare module.exports: $Exports<'parse-duration'>;
}
declare module 'parse-duration/index.js' {
  declare module.exports: $Exports<'parse-duration'>;
}
