// flow-typed signature: a1a2e2c08ab5f173fcd708c3827f3dfb
// flow-typed version: <<STUB>>/signale_v^1.4.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'signale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'signale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'signale/signale' {
  declare module.exports: any;
}

declare module 'signale/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'signale/index' {
  declare module.exports: $Exports<'signale'>;
}
declare module 'signale/index.js' {
  declare module.exports: $Exports<'signale'>;
}
declare module 'signale/signale.js' {
  declare module.exports: $Exports<'signale/signale'>;
}
declare module 'signale/types.js' {
  declare module.exports: $Exports<'signale/types'>;
}
